import { createClient } from "@/lib/supabase/server";
import { Sparkles, Clock, FileText, CheckCircle, Play, Calendar, Target, Zap } from "lucide-react";
import Link from "next/link";

interface DailyTest {
    id: string;
    title: string;
    exam_category: string;
    subject: string;
    difficulty: string;
    questions_count: number;
    duration_minutes: number;
    test_date: string;
}

interface TestAttempt {
    daily_test_id: string;
    score: number;
    completed_at: string;
}

const categoryColors: Record<string, string> = {
    "SSC": "from-blue-500 to-cyan-500",
    "Railway": "from-green-500 to-emerald-500",
    "Bank": "from-purple-500 to-pink-500",
    "RPSC": "from-orange-500 to-red-500",
    "Police": "from-red-500 to-rose-500",
    "RSMSSB": "from-cyan-500 to-teal-500",
};

export default async function DailyPracticePage() {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    // Fetch today's tests
    const today = new Date().toISOString().split("T")[0];
    const { data: todayTests } = await supabase
        .from("generated_daily_tests")
        .select("*")
        .eq("status", "published")
        .eq("test_date", today)
        .order("exam_category") as { data: DailyTest[] | null };

    // Fetch recent tests (last 7 days)
    const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0];
    const { data: recentTests } = await supabase
        .from("generated_daily_tests")
        .select("*")
        .eq("status", "published")
        .gte("test_date", weekAgo)
        .lt("test_date", today)
        .order("test_date", { ascending: false })
        .limit(20) as { data: DailyTest[] | null };

    // Fetch user's attempts
    const { data: attempts } = await supabase
        .from("daily_test_attempts")
        .select("daily_test_id, score, completed_at")
        .eq("user_id", user?.id) as { data: TestAttempt[] | null };

    const attemptedTestIds = new Set(attempts?.map(a => a.daily_test_id) || []);
    const attemptScores = new Map(attempts?.map(a => [a.daily_test_id, a.score]) || []);

    return (
        <div className="max-w-6xl mx-auto px-4 py-8">
            {/* Header */}
            <div className="text-center mb-8">
                <div className="inline-flex items-center gap-2 bg-gradient-to-r from-yellow-100 to-orange-100 text-yellow-700 px-4 py-2 rounded-full text-sm font-medium mb-4">
                    <Sparkles size={16} />
                    AI-Powered Daily Practice
                </div>
                <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-2">
                    Daily Practice Tests
                </h1>
                <p className="text-gray-500 max-w-2xl mx-auto">
                    Free daily practice tests generated by AI for government exam preparation.
                    10 quick questions to sharpen your skills every day!
                </p>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-3 gap-4 mb-8">
                <div className="bg-white rounded-xl p-4 shadow-sm border text-center">
                    <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-2">
                        <Target className="text-blue-600" size={24} />
                    </div>
                    <p className="text-2xl font-bold text-gray-900">{todayTests?.length || 0}</p>
                    <p className="text-sm text-gray-500">Today's Tests</p>
                </div>
                <div className="bg-white rounded-xl p-4 shadow-sm border text-center">
                    <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-2">
                        <CheckCircle className="text-green-600" size={24} />
                    </div>
                    <p className="text-2xl font-bold text-gray-900">{attempts?.length || 0}</p>
                    <p className="text-sm text-gray-500">Tests Completed</p>
                </div>
                <div className="bg-white rounded-xl p-4 shadow-sm border text-center">
                    <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-2">
                        <Zap className="text-purple-600" size={24} />
                    </div>
                    <p className="text-2xl font-bold text-gray-900">🆓</p>
                    <p className="text-sm text-gray-500">Always Free</p>
                </div>
            </div>

            {/* Today's Tests */}
            <section className="mb-12">
                <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 bg-gradient-to-br from-yellow-400 to-orange-500 rounded-xl flex items-center justify-center">
                        <Calendar className="text-white" size={20} />
                    </div>
                    <div>
                        <h2 className="text-xl font-bold text-gray-900">Today's Practice Tests</h2>
                        <p className="text-sm text-gray-500">{new Date().toLocaleDateString("en-IN", { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}</p>
                    </div>
                </div>

                {todayTests && todayTests.length > 0 ? (
                    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
                        {todayTests.map((test) => {
                            const isAttempted = attemptedTestIds.has(test.id);
                            const score = attemptScores.get(test.id);

                            return (
                                <div
                                    key={test.id}
                                    className={`bg-white rounded-2xl overflow-hidden shadow-sm border hover:shadow-lg transition ${isAttempted ? "ring-2 ring-green-500" : ""
                                        }`}
                                >
                                    <div className={`h-2 bg-gradient-to-r ${categoryColors[test.exam_category] || "from-gray-400 to-gray-500"}`} />
                                    <div className="p-5">
                                        <div className="flex items-center justify-between mb-3">
                                            <span className="text-xs font-medium bg-gray-100 text-gray-700 px-2 py-1 rounded">
                                                {test.exam_category}
                                            </span>
                                            {isAttempted && (
                                                <span className="flex items-center gap-1 text-xs font-medium bg-green-100 text-green-700 px-2 py-1 rounded">
                                                    <CheckCircle size={12} />
                                                    Score: {score}/{test.questions_count}
                                                </span>
                                            )}
                                        </div>

                                        <h3 className="font-bold text-gray-900 mb-1">{test.subject}</h3>

                                        <div className="flex items-center gap-3 text-sm text-gray-500 mb-4">
                                            <span className="flex items-center gap-1">
                                                <FileText size={14} />
                                                {test.questions_count} Qs
                                            </span>
                                            <span className="flex items-center gap-1">
                                                <Clock size={14} />
                                                {test.duration_minutes} min
                                            </span>
                                            <span className={`px-1.5 py-0.5 rounded text-xs ${test.difficulty === "easy" ? "bg-green-100 text-green-700" :
                                                    test.difficulty === "medium" ? "bg-yellow-100 text-yellow-700" :
                                                        "bg-red-100 text-red-700"
                                                }`}>
                                                {test.difficulty}
                                            </span>
                                        </div>

                                        <Link
                                            href={`/daily-practice/${test.id}`}
                                            className={`w-full flex items-center justify-center gap-2 py-2.5 rounded-xl font-medium transition ${isAttempted
                                                    ? "bg-gray-100 text-gray-700 hover:bg-gray-200"
                                                    : "bg-gradient-to-r from-primary-600 to-blue-600 text-white hover:shadow-lg"
                                                }`}
                                        >
                                            <Play size={16} />
                                            {isAttempted ? "View Result" : "Start Test"}
                                        </Link>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                ) : (
                    <div className="bg-white rounded-2xl p-10 text-center shadow-sm border">
                        <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                            <Calendar className="text-gray-400" size={32} />
                        </div>
                        <h3 className="font-semibold text-gray-900 mb-2">No tests available today</h3>
                        <p className="text-gray-500">Check back later or try previous tests below</p>
                    </div>
                )}
            </section>

            {/* Previous Tests */}
            {recentTests && recentTests.length > 0 && (
                <section>
                    <div className="flex items-center gap-3 mb-6">
                        <div className="w-10 h-10 bg-gradient-to-br from-gray-400 to-gray-600 rounded-xl flex items-center justify-center">
                            <Clock className="text-white" size={20} />
                        </div>
                        <div>
                            <h2 className="text-xl font-bold text-gray-900">Previous Tests</h2>
                            <p className="text-sm text-gray-500">Practice with tests from the past week</p>
                        </div>
                    </div>

                    <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
                        {recentTests.map((test) => {
                            const isAttempted = attemptedTestIds.has(test.id);
                            const score = attemptScores.get(test.id);

                            return (
                                <Link
                                    key={test.id}
                                    href={`/daily-practice/${test.id}`}
                                    className="bg-white rounded-xl p-4 shadow-sm border hover:shadow-md transition"
                                >
                                    <div className="flex items-center justify-between mb-2">
                                        <span className="text-xs font-medium bg-gray-100 text-gray-600 px-2 py-0.5 rounded">
                                            {test.exam_category}
                                        </span>
                                        <span className="text-xs text-gray-400">
                                            {new Date(test.test_date).toLocaleDateString("en-IN", { day: 'numeric', month: 'short' })}
                                        </span>
                                    </div>
                                    <h3 className="font-medium text-gray-900 text-sm mb-2">{test.subject}</h3>
                                    <div className="flex items-center justify-between">
                                        <span className="text-xs text-gray-500">{test.questions_count} Qs</span>
                                        {isAttempted ? (
                                            <span className="text-xs text-green-600 font-medium">
                                                ✓ {score}/{test.questions_count}
                                            </span>
                                        ) : (
                                            <span className="text-xs text-primary-600 font-medium">
                                                Start →
                                            </span>
                                        )}
                                    </div>
                                </Link>
                            );
                        })}
                    </div>
                </section>
            )}
        </div>
    );
}
